version: '3.4'

services:
  # db:
  #  image: chameleon82/oracle-xe-10g:latest
  #  environment:
  #    - ORACLE_PASSWORD=password
  #  ports:
  #    - 49161:1521
  dbfit:
    image: ministryofjustice/dbfit:3.2-jre11
    ports:
      - 8085:8085
    volumes:
      - ./TestSuite:/dbfit/FitNesseRoot/TestSuite
      - ./oracle.properties:/dbfit/oracle.properties
      - ./plugins.properties:/dbfit/plugins.properties
      - ./Dependencies/ojdbc6-11.2.0.4.jar:/dbfit/lib/ojdbc6-11.2.0.4.jar
      - ./ProfilerHelper:/ProfilerHelper
    command: /bin/sh -c 'cd dbfit && ./startFitnesse.sh'
  dbfit-m1:
    image: ministryofjustice/dbfit:3.2-jre11-arm64
    ports:
      - 8085:8085
    volumes:
      - ./TestSuite:/dbfit/FitNesseRoot/TestSuite
      - ./oracle.properties:/dbfit/oracle.properties
      - ./plugins.properties:/dbfit/plugins.properties
      - ./Dependencies/ojdbc6-11.2.0.4.jar:/dbfit/lib/ojdbc6-11.2.0.4.jar
      - ./ProfilerHelper:/ProfilerHelper
    command: /bin/sh -c 'cd dbfit && ./startFitnesse.sh'